### ISSUE TITLE
Disabling SmoothMode for some HTML classes may solve typing lag issues in large projects

### ISSUE THREAD

**Issue by Seng-Jik** [BrandonKirbyson/VSCode-Animations#58]
It is known that using SmoothMode in the following programming language environments can cause lag issues when typing and popping suggestions:

* Rust+rust analyzer
* C #+ NET 8.0+C # Dev+C # extension
* C #+Unity+C # Dev+C # extension
* F #+ NET 8.0+C # Dev+Ionide

SmoothMode will work properly in the following programming languages:

* C
* Haskell

Based on experience, lagging may be related to suggestion pop windows. You can try turning off support for suggestion in SmoothMode to get a good typing experience.

![image](https://github.com/BrandonKirbyson/VSCode-Animations/assets/11296891/8bc2242f-68c3-46d3-bdbc-c9f6d00f3b82)

This message was translated using machine translation. I apologize for any inappropriate expressions.

**Comment by Seng-Jik** [comment]
https://github.com/BrandonKirbyson/VSCode-Animations/assets/11296891/47916609-c3f2-4392-9261-00b59421f8cb

**Comment by Seng-Jik** [comment]
I suggest SmoothMode not to use the "Exclude" method to specify the classes to be animated, but to use the "Include" method to specify which classes to be animated, so that both performance and animation performance are more controllable.

**Comment by BrandonKirbyson** [comment]
Thank you for all the information, I tested it out and turns out smooth mode is already fully disabled in the suggestion popups. It is most likely this is then caused because of so many other elements having css transitions. I'll keep looking into this but that's just a quick update.

**Comment by BrandonKirbyson** [comment]
I just published a new version that fixed a couple other things, could you maybe check if it's working any better for you?

**Comment by Seng-Jik** [comment]
> I just published a new version that fixed a couple other things, could you maybe check if it's working any better for you?

Thank you for your efforts. v2.0.2 did not solve the problem of typing lag.

**Comment by BrandonKirbyson** [comment]
Ok thanks for checking that, I'll keep looking into it.

**Comment by Seng-Jik** [comment]
This issue seemed to have been non-existent or relatively minor in the previous version of vscode, until it suddenly became more severe after a certain version was released later.

**Comment by Seng-Jik** [comment]
In version 2.0.2, lag seems to have been alleviated.
